
services:
  - docker

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-api-feed loui4/udagram-api-feed:v1
  - docker tag udagram-api-user loui4/udagram-api-user:v1
  - docker tag udagram-frontend loui4/udagram-frontend:v1
  - docker tag reverseproxy loui4/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push loui4/udagram-api-feed:v1
  - docker push loui4/udagram-frontend:v1
  - docker push loui4/udagram-api-user:v1
  - docker push loui4/reverseproxy:v1